### ISSUE TITLE
Unsure of how to register template classes outside of their class.

### ISSUE THREAD

**Issue by squidt** [eliasdaler/MetaStuff#13]
When registering a template class in MetaStuff (outside of the class) one has to declare the template arguments, I assumed, like so:
```
template <class Param1, typename Param2>
inline auto registerMembers<TemplateClass<Param1, Param2>>()
{
    return members(
        member("example", &TemplateClass<Param1, Param2>::example)
    );
}
```
But this produces the error: "'meta::registerMembers': illegal use of explicit template arguments", since the function is originally supposed to be declared like this:
```
template <>
inline auto registerMembers<(class here)>()
{
    // ... stuff goes here
}
```
which begs the question for me, how would someone register a class that takes templates?

**Comment by eliasdaler** [comment]
```c++
template<>
template <class Param1, typename Param2>
inline auto registerMembers<TemplateClass<Param1, Param2>>()
{
    return members(
        member("example", &TemplateClass<Param1, Param2>::example)
    );
}
```

Try this. Template stuff can be tricky sometimes. :D

**Comment by NothingInParticular** [comment]
Even with this code, I'm still getting two errors:
"'meta::registerMembers': illegal use of explicit template arguments"
and
"'meta::registerMembers': cannot be explicitly specialized"

**Comment by eliasdaler** [comment]
Looks like doing stuff with functions which I want to do is not possible in C++.
I think that it's partial template function specialization which is not allowed. I think it'll be possible if I make registerMembers a static function of some dummy struct... I'll have to try it out. I'm glad that you've found the problem with the design.

And glad that you like using it so far. :)

**Comment by eliasdaler** [comment]
Ok, so it looks like this will work (can't make this code work without using empty structures!)

```c++
#include <iostream>

// this will be in MetaStuff...

template <typename T>
struct MetaRegistrator
{
    static void registerMembers() {
        std::cout << "Register some type" << std::endl;
    }
};

// Your struct you want to register
template <typename T>
struct S {
    T obj;
};

// Your registration code in the future
template <typename T>
struct MetaRegistrator<S<T>>
{
    static void registerMembers()
    {
        std::cout << "Register S<T>" << std::endl;
    }
};

int main()
{
    // You won't actually need to call them later
    MetaRegistrator<S<int>>::registerMembers();
    MetaRegistrator<int>::registerMembers();
}
```

**Comment by eliasdaler** [comment]
I think this may lead to some extended capabilities of MetaStuff... maybe you'll be able to hold more info about the class than about members...

(E.g. storing class's name by defining it in MetaRegistrator as a static member?)

**Comment by NothingInParticular** [comment]
Definitely cool stuff. Going to try it out asap.

**Comment by eliasdaler** [comment]
Hello
Can I close the issue?
