### ISSUE TITLE
Easy way to get the number of registered members?

### ISSUE THREAD

**Issue by w1th0utnam3** [eliasdaler/MetaStuff#15]
For some applications it is necessary to get the number of registered members of a type. This is possible using
```c++
std::tuple_size<decltype(registerMembers<Class>())>::value
```
This is however an implementation detail which may not be ideal to rely on from the outside. The alternative
```c++
std::tuple_size<std::decay_t<decltype(getMembers<Class>())>>::value
```
is way too verbose. Therefore, I would propose to add a new function
```c++
template <typename Class>
constexpr std::size_t getMemberCount();
```
with the definition
```c++
template <typename Class>
constexpr std::size_t getMemberCount()
{
	return std::tuple_size<decltype(registerMembers<Class>())>::value;
}
```
to your meta library.

**Comment by w1th0utnam3** [comment]
Alternatively, this could be provided without a function:
```
// integral constant containing the number of registered Members
template <typename Class>
using get_member_count = std::tuple_size<decltype(registerMembers<Class>())>;

// number of registered Members
template <typename Class>
inline constexpr std::size_t get_member_count_v = get_member_count<Class>::value;
```

**Comment by eliasdaler** [comment]
Good idea. Please make a PR, and I'll accept it.

Just curious: what will you use it for?

**Comment by w1th0utnam3** [comment]
Sure, do you prefer the constexpr function or the alias template + inline variable? I'm currently using the latter.

In general, I use MetaStuff to deserialize objects from CSV files using ["Fast C++ CSV Parser"](https://github.com/ben-strasser/fast-cpp-csv-parser). I need the number of registered members as the parser requires the number of expected CSV columns (-> registered data members) as a template parameter. Furthermore, I wrote two functions
```c++
// returns std::tuple of all member names (const char*)
template <typename Class>
const auto& getMemberNames();

// returns std::tuple containing a reference for each member
template <typename Class>
auto getMemberRefTuple(Class&& obj);
```
which also make use of the number of members.  The CSV lib has a `read_row` function which takes a reference for each column, where the read values are written to:
```c++
int a,b;
while(csvReader.read_row(a,b)){
    // a contains value of first column, b of the second column...
}
```
I use the `getMemberRefTuple` function in combination with `std::apply` to directly deserialize each row into an instance of the registered type.

**Comment by eliasdaler** [comment]
Oh, nice to see my lib being used this way. :)

I think that constexpr function is easier to read, so I'd prefer it.

**Comment by w1th0utnam3** [comment]
Cool, see https://github.com/eliasdaler/MetaStuff/pull/16.

**Comment by eliasdaler** [comment]
Merged, thanks.
