### ISSUE TITLE
clang-based generator

### ISSUE THREAD

**Issue by w0land** [eliasdaler/MetaStuff#18]
Hi, 

This is not an issue rather a small improvement. 

I found it very annoying to manually type template specialization for custom types so
I've implemented a simple clang-based generator that does it for you. 
See [https://github.com/w0land/metastuff-clang-generator](https://github.com/w0land/metastuff-clang-generator). 

thanks for a **great** library!

**Comment by eliasdaler** [comment]
Wow, that's really amazing! I'll add a link to it in readme. 
And as I start working on MetaStuff again, I'll probably break some stuff, so I'll be sure to notify you about breaking changes.

**Comment by eliasdaler** [comment]
By the way, can it work with getters/setters somehow?

**Comment by w0land** [comment]
@eliasdaler not yet, as I need to figure out how to approach this ;)
Code documentation? What do you think?

**Comment by eliasdaler** [comment]
I don't think it can be dealt with, to be honest. No way to easily identify which functions are getters/setters for a variable, unless it's specified in comments and then your tool will parse this comments.

But this feels very hacky!
