### ISSUE TITLE
Support for methods

### ISSUE THREAD

**Issue by Nightmare82** [eliasdaler/MetaStuff#20]
One thing that would be nice is to have the possibility to define methods that can afterwards be called using your library. A use case for that is that developers can define methods than can be called via GUI in a game editor, for example functions like "Reset" for a component.

I tried to use the existing mechanics but it crashes when trying to call the method:

Struct Test
{
  void test(int parameter) { std::cout << "Called test with parameter: " << parameter << std::endl;
}:

namespace meta
{
    template <>
    inline auto registerMembers<Test>()
    {
        return members(member("test", &Test::test));
    }
}

Test testObject;
meta::setMemberValue<Test>(testObject, "test", 12);

I think ideally it would work similar as members, e.g. :

namespace meta
{
    template <>
    inline auto registerMembers<Test>()
    {
        return members(method("test", &Test::test),member("x", &Test::getX));
    }
}

Test testObject;
meta::callMethod<Test>(testObject, "test", 12);

What do you think ?

**Comment by Nightmare82** [comment]
Oh, I just found out it is working already with members, I just used the wrong template parameter :-)

This is the working version:
Struct Test
{
void test(int parameter) { std::cout << "Called test with parameter: " << parameter << std::endl;
}:

namespace meta
{
template <>
inline auto registerMembers()
{
return members(member("test", &Test::test));
}
}

Test testObject;
meta::setMemberValue<int>(testObject, "test", 12);

**Comment by eliasdaler** [comment]
Yup, it works. Same for the getters. :D

**Comment by Nightmare82** [comment]
Is there any trick to make it work with methods without parameters or with multiple parameters ?(Multiple parameters aren't necessary in my case but methods without parameters would be nice)

**Comment by Nightmare82** [comment]
Sure, that’s fine.
