### ISSUE TITLE
Question: Does this library support class hierarchies?

### ISSUE THREAD

**Issue by heretique** [eliasdaler/MetaStuff#21]
Hi, I've stumbled upon your library and I really like the ease of use and I would like to use it instead of Cereal, the library I currently use for serialization. Does MetaStuff support class hierarchies/inheritance out of the box and if not is there any planed support for this?

**Comment by eliasdaler** [comment]
Hello

Is this what you want?

https://gist.github.com/eliasdaler/45bf3f583cd4a41019b9802c198e6f41

**Comment by heretique** [comment]
Yes, that's exactly what I want, so it is possible. Thanks

**Comment by eliasdaler** [comment]
I don't know if it's possible to make, to be honest. The inheritance tree can get pretty deep, and the library will need to traverse it somehow, while concatenating each tuple of the class on its way... Maybe with reflection in C++2x this will be somewhat possible. :)

**Comment by heretique** [comment]
[This](https://stackoverflow.com/a/8709647) stackoverflow and [this](http://rextester.com/discussion/MIM59300/How-to-get-base-class) snippet might give some partial solution. I don't know of any other more generic solution.

**Comment by eliasdaler** [comment]
Yeah, but one of these methods requires base to have a function that's present in a base class, but not in derived class. The other methods require you to add some typedefs into classes, which is not good.

At this point, it's much easier to specify which base classes you want to get members ;)
It's implicit, short and non-intrusive (doesn't require you to modify original classes).

**Comment by heretique** [comment]
Totally agree.
