### ISSUE TITLE
Working with classes unkown at compile time ? (PropertyGrid for components)

### ISSUE THREAD

**Issue by Nightmare82** [eliasdaler/MetaStuff#22]
Hi,

I would like to implement a PropertyGrid for an array of components which contain any properties. The problem is that I don't know the type of them at compile time and the code also can't be put into virtual functions of a component because the components shouldn't know about the UI.

Is there any trick how I can do that cleanly ? Pseudo code would be something like that:

```
Component* component = ...;
for (Property& property : component)
{
  if (property.is<std::string>())
  {
    // show EditBox
  }
  else if (property.is<int>())
  {
    // show numeric EditBox
  }
  // ...
}
```

Previously I worked with ponder which uses the same data structure for every type so it was easy to do, I hope I can also accomplish that with MetaStuff.

**Comment by eliasdaler** [comment]
I think that something like this should work:

```template <typename Class>
void PropertyGrid::createPropertyGrid(const Class& obj)
{
    meta::doForAllMembers<Class>(
        [&obj, this](auto& member)
        {
            if (member.canGetRef()) {
                this->addRow(member.getName(), member.getRef(obj));
            }
        }
    );
}

template <typename T>
void PropertyGrid::addRow(T&, const char*)
{ }

template <>
void PropertyGrid::addRow<std::string>(std::string& obj, const char* name)
{
    ... // show EditBox
}

template <>
void PropertyGrid::addRow<int>(int& obj, const char* name)
{
    ... // show numeric EditBox
}```

**Comment by Nightmare82** [comment]
Thanks for your reply! This part is clear for me but the problem is that I have a lot of components in the game and the only way to implement something like a property grid is to add code like that as far as I can see currently:

If (component->is<TestComponent>)
{
 // static cast to test component and call the template function with it
}
// do the same for all other component types

Do you know of any better solution ? The only alternative I can think of is a generic method in my component with some functors as parameters(one for each datatype) but that doesn’t sound clean either regarding the usage.

**Comment by eliasdaler** [comment]
Yeah, in your case you deal with type erasure in Components, which you can deal with by two methods:

1) Make some class (e.g. named ComponentRegistrator) and have it store:

```cpp
std::unordered_map<std::type_index, std::function<void(*)(Component&, PropertyGrid&)> functions;
```

And then you do something like this:

```cpp
template <typename T>
void ComponentRegistrator::addComponentType()
{
    functions.emplace_back({
        std::type_index(typeid(T)),
        [](Component& c, PropertyGrid& pg)
        {
            pg.addRow(static_cast<T>(c));
        }
    });
}

void ComponentRegistrator::registerAllComponents()
{
    addComponentType<TestComponent>();
    addComponentType<MeshComponent>();
}
```

2) CRTP:

```cpp
class ComponentBase
{
public:
    virtual addPropertyGridRow(PropertyGrid&) = 0;
};

template <typename T>
class Component : public ComponentBase
{
public:
    void addPropertyGridRow(PropertyGrid& pg) override 
    {
        pg.addRow(static_cast<T>(*this));
    }
};
```

And then you'll make your components like this:

```cpp
class MeshComponent : public Component<MeshComponent>
{
    ...
};
```

Now, when you'll call `addPropertyGridRow` on `ComponentBase`, it'll make a static_cast to a derived type automatically.

**Comment by Nightmare82** [comment]
OK, thanks for the details!

I currently already use the second approach(CRTP) for my components but components shouldn't know about the UI but I guess I'll implement something like the first approach with some code generation.

Thanks!
