### ISSUE TITLE
Want to write a class member variable and a struct variable ( this structure is inside the class) to the json file

### ISSUE THREAD

**Issue by quicksilver345** [eliasdaler/MetaStuff#24]
I have a class and inside that class i have a struct, now i want to write the class variable "name" and the structure member "a" in the json file but i am not able to do so, can you please help me with the problem. :-
(Using same code as of your example -> simple_meta_info_class.cpp -> https://gist.github.com/eliasdaler/213d42051958ae21185adbc7edbff915)
My Code snipet ->

```c++
class ABC
{
public:
    struct ex
    {
        public:
            int a;
    };

    static void registerclass()
    {
        ClassMetaInfo<ABC>::registerMember("name", &ABC::name);
        ClassMetaInfo<ex>::registerMember("int a ", &ex::a);
    }

    std::string name;
    ex var = { };  
};
```

json file output :-
```json
{
    "name": "JOHN"
}
```

By the above code i am getting the class variable "name" written in the json file but cannot see the structure variable "a" in the json file.

I have tried to put the registerclass() method inside the structure also but still i am not getting the stucture variable "a" written in my json file

(I want to write both the class variable and the structure variable in the json file, as per the above example i am expecting something like :-

```json
{
    "name": "JOHN",
    "int a" : 32 
}
```

to be the json output

Can you please help me regarding the issue
(Compiling on a windows machine in visual studio 2017)

**Comment by quicksilver345** [comment]
Actually i am referring this code -> https://gist.github.com/eliasdaler/213d42051958ae21185adbc7edbff915

and in place of ->
struct Person {
std::string name;
int age;
}; in the code as in the link above, i am having this scenario ( nested structure)->

struct second
{
int secondID;
};
struct Person {
public:
int firstID;
second objsec;
};
( I have changed only the structure from the link given above to a nested structure )
Now i want my output to be something like this ->
{
"firstID": 2
"secondID": 3
}

**Comment by eliasdaler** [comment]
Hello.

First of all, in your first example ABC::ex is a just type which needs to be registered to be serializable. It's not a part of ABC. Unless you store ABC::ex in ABC, there'll be no object to serialize.

So, here's one thing you can do:

```c++
struct ABC {
    struct ex {
        int a;
   }
   
   ex b;
}
```

Now you can do this:

```c++
template <>
inline auto registerMembers<ABC>()
{
    return members(
        member("b", &ABC::b)
    );
}

template <>
inline auto registerMembers<ABC::ex>()
{
    return members(
        member("a", &ABC::ex::a)
    );
}
```

And you'll get a JSON like this:

```json
{
    "b" : {
        "a" : 50
    }
}
```

Now, suppose you want to get this instead (no "inner" level)

```json
{
    "a" : 50
}
```

This is possible too! But you'll have to do this instead

```c++
struct ABC {
    struct ex {
        int a;
   }
   
   int getA() const { return b.a; }

   ex b;
}
```

And then...

```cpp
template <>
inline auto registerMembers<ABC>()
{
    return members(
        member("a", &ABC::getA)
    );
}
```

And this will give you a flat structure you probably want.

This makes me think that adding support of lambda functions for getters/setters would be very useful as it will allow you to do something like:

```cpp
template <>
inline auto registerMembers<ABC>()
{
    return members(
        member("a", [](const ABC& obj) { return obj.b.a; })
    );
}
```

and not have to introduce additional getters/setters to your types. I'll see what I can do. :)

**Comment by eliasdaler** [comment]
Hello. So, here's what you can do:

```c++
struct second
{
    int secondID;
};

struct Person {
public:
    int firstID;
    second objsec;

    int getSecondId() const { return objsec.secondId; }
};


namespace meta
{

template <>
inline auto registerMembers<Person>()
{
    return members(
        member("firstID", &Person::firstId), 
        member("secondID", &Person::getSecondId)
    );
}

}
```

Note that you'll need to add a getter for the secondID, otherwise this won't work (but this approach would also work for you first example where you have an inner class).

This makes me think that supporting lambda/free functions for getters/setters would be pretty cool, so that you'll be able to do just this:

```c++
template <>
inline auto registerMembers<Person>()
{
    return members(
        member("firstID", &Person::firstId), 
        member("secondID", [](const Person& p) { return p.objsec.secondId;})
    );
}
```

without having to add a getter to `Person`. I'll try to implement it. :)
