### ISSUE TITLE
Ability to register members outside of meta namespace

### ISSUE THREAD

**Issue by gouletr** [eliasdaler/MetaStuff#27]
Hi, I have been playing with your library and found it very constraining to be forced into defining the `registerMembers` specialization in the `meta` namespace. Of course, its an explicit function template specialization, so its just how C++ works.

But what if I can't declare it in the `meta` namespace? For instance, I am combining your lib with [Cereal](http://uscilab.github.io/cereal/index.html), a very nice serialization lib, which have the constraint that the serialization methods must be defined either in the serialized class namespace or the `cereal` namespace.

Quickly this becomes very annoying, especially if we want to just register members and the serialization function in a single macro.

I was able to workaround around it by declaring an overload function instead of an explicit function template specialization:
```cpp
template<typename Class>
inline auto registerMembers(const Class&);
```

and then have the Meta.inl functions call that overload instead:
```cpp
template<typename Class>
const Class&
toReference(const Class* c)
{
    return *c;
}

template<typename Class>
constexpr auto
getName()
{
    return MetaInfoContainer<Class, decltype(registerMembers(toReference<Class>(nullptr)))>::name();
}
```

of course the null reference trick is kinda ugly, and I am not sure this still qualify as a proper constexpr anymore, but it seems to work.

What are your thoughts?
Cheers!

**Comment by eliasdaler** [comment]
Hello. Sorry, I completely forgot about this issue! I think I figured out a way to do it.
I can make it so you need to put `registerMembers` into the same namespace as type being registered and you'll also need to put dummy `TypeTag` as a parameter for `registerMembers` for ADL to work. Is it ok?

See the example:

```cpp
#include <iostream>

template <typename T>
struct TypeTag {};

template <typename T>
void registerMembers(TypeTag<T>)
{
    std::cout << "Generic" << std::endl;
}

namespace Graphics
{
    struct Sprite {};
    
    void registerMembers(TypeTag<Sprite>) 
    {
        std::cout << "Specialized for X" << std::endl;
    }
}

template <typename T>
void serialize()
{
    registerMembers(TypeTag<T>{});
}

int main()
{
    serialize<int>();
    serialize<Graphics::Sprite>();
}
```

**Comment by gouletr** [comment]
That is what I ended up doing, it worked fine. Though later we realized that doing these constexpr templates increased the code size dramatically so we had to choose a different strategy altogether. Nonetheless, this is very insightful code, thanks for this!

**Comment by eliasdaler** [comment]
So, is the current version good enough? Or do I need to make some changes to make your life easier?

**Comment by gouletr** [comment]
No changes needed, we can close this. Thanks!
