### ISSUE TITLE
example build errors on cent7 using devtoolkit-4 (g++ 5.3.1)

### ISSUE THREAD

**Issue by brewc983** [eliasdaler/MetaStuff#29]
Hi Elias,

I really like your implementation. It is a very well thought out design and is easy to implement. I would like to include it for use in serializing some legacy C structures to JSON for C++ to JAVA communications.

I tried to build the example code on cent7 using g++ 5.3.1 but I am getting the errors shown below. 

<b>***note ***</b>
I had to first modify main.cpp to include iomanip. 

Any thoughts?

Thanks,
Bruce

<b> Makefile i used for the build</b>
<pre>
COMMON_FLAGS=-std=c++14 -Wall  
INCL=-I./ -I../include

SOURCES=$(wildcard *.cpp)
DEPENDS=$(patsubst %cpp,%d,$(SOURCES))
OBJECTS=$(patsubst %cpp,%o,$(SOURCES))

.PHONY: clean all remake

meta_stuff_example: $(OBJECTS)
	g++ $(COMMON_FLAGS) $^ -o meta_stuff_example
	@echo meta_stuff_example done

all: meta_stuff_example
	@echo all done

remake: clean all

clean:
	@rm -f *.d *.o meta_stuff_example

%.o: %.cpp
	g++ $(COMMON_FLAGS) -c $(INCL) -o $*.o $<

-include $(DEPENDS)

%.d: $(SOURCES)
	g++ -std=c++14 -M $(INCL) $< | sed 's,\($(notdir $*)\.o\) *:,$(dir $@)\1 $@: ,g' > $@\.tmp
	@mv $@.tmp $@_
</pre>

<b>build --- errors ----</b>
<pre>
g++ -std=c++14 -Wall   -c -I./ -I../include -o main.o main.cpp
In file included from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/stl_algobase.h:64:0,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/char_traits.h:39,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/ios:40,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/ostream:38,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/iostream:39,
                 from main.cpp:1:
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/stl_pair.h: In instantiation of ‘constexpr std::pair<_T1, _T2>::pair(_U1&&, _U2&&) [with _U1 = std::basic_string<char>; _U2 = const nlohmann::basic_json<>&; <template-parameter-2-3> = void; _T1 = const std::basic_string<char>; _T2 = std::vector<MovieInfo>]’:
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/ext/new_allocator.h:120:4:   required from ‘void __gnu_cxx::new_allocator<_Tp>::construct(_Up*, _Args&& ...) [with _Up = std::pair<const std::basic_string<char>, std::vector<MovieInfo> >; _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, const nlohmann::basic_json<std::map, std::vector, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer>&}; _Tp = std::pair<const std::basic_string<char>, std::vector<MovieInfo> >]’
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/alloc_traits.h:530:4:   required from ‘static void std::allocator_traits<std::allocator<_CharT> >::construct(std::allocator_traits<std::allocator<_CharT> >::allocator_type&, _Up*, _Args&& ...) [with _Up = std::pair<const std::basic_string<char>, std::vector<MovieInfo> >; _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, const nlohmann::basic_json<std::map, std::vector, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer>&}; _Tp = std::pair<const std::basic_string<char>, std::vector<MovieInfo> >; std::allocator_traits<std::allocator<_CharT> >::allocator_type = std::allocator<std::pair<const std::basic_string<char>, std::vector<MovieInfo> > >]’
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/hashtable_policy.h:1955:37:   required from ‘std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type* std::__detail::_Hashtable_alloc<_NodeAlloc>::_M_allocate_node(_Args&& ...) [with _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, const nlohmann::basic_json<std::map, std::vector, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer>&}; _NodeAlloc = std::allocator<std::__detail::_Hash_node<std::pair<const std::basic_string<char>, std::vector<MovieInfo> >, true> >; std::__detail::_Hashtable_alloc<_NodeAlloc>::__node_type = std::__detail::_Hash_node<std::pair<const std::basic_string<char>, std::vector<MovieInfo> >, true>]’
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/hashtable.h:1526:77:   required from ‘std::pair<typename std::__detail::_Hashtable_base<_Key, _Value, _ExtractKey, _Equal, _H1, _H2, _Hash, _Traits>::iterator, bool> std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::_M_emplace(std::true_type, _Args&& ...) [with _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, const nlohmann::basic_json<std::map, std::vector, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer>&}; _Key = std::basic_string<char>; _Value = std::pair<const std::basic_string<char>, std::vector<MovieInfo> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::vector<MovieInfo> > >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::basic_string<char> >; _H1 = std::hash<std::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; typename std::__detail::_Hashtable_base<_Key, _Value, _ExtractKey, _Equal, _H1, _H2, _Hash, _Traits>::iterator = std::__detail::_Node_iterator<std::pair<const std::basic_string<char>, std::vector<MovieInfo> >, false, true>; std::true_type = std::integral_constant<bool, true>]’
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/hashtable.h:726:21:   required from ‘std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__ireturn_type std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::emplace(_Args&& ...) [with _Args = {std::basic_string<char, std::char_traits<char>, std::allocator<char> >, const nlohmann::basic_json<std::map, std::vector, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool, long int, long unsigned int, double, std::allocator, nlohmann::adl_serializer>&}; _Key = std::basic_string<char>; _Value = std::pair<const std::basic_string<char>, std::vector<MovieInfo> >; _Alloc = std::allocator<std::pair<const std::basic_string<char>, std::vector<MovieInfo> > >; _ExtractKey = std::__detail::_Select1st; _Equal = std::equal_to<std::basic_string<char> >; _H1 = std::hash<std::basic_string<char> >; _H2 = std::__detail::_Mod_range_hashing; _Hash = std::__detail::_Default_ranged_hash; _RehashPolicy = std::__detail::_Prime_rehash_policy; _Traits = std::__detail::_Hashtable_traits<true, false, true>; std::_Hashtable<_Key, _Value, _Alloc, _ExtractKey, _Equal, _H1, _H2, _Hash, _RehashPolicy, _Traits>::__ireturn_type = std::pair<std::__detail::_Node_iterator<std::pair<const std::basic_string<char>, std::vector<MovieInfo> >, false, true>, bool>]’
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/unordered_map.h:380:54:   [ skipping 15 instantiation contexts, use -ftemplate-backtrace-limit=0 to disable ]
JsonCast.inl:12:22:   required from ‘void from_json(const json&, T&) [with T = Person; json = nlohmann::basic_json<>]’
./nlohmann_json/json.hpp:1290:25:   required from ‘decltype ((nlohmann::detail::from_json(j, val), void())) nlohmann::detail::from_json_fn::call(const BasicJsonType&, T&, nlohmann::detail::priority_tag<1u>) const [with BasicJsonType = nlohmann::basic_json<>; T = Person; decltype ((nlohmann::detail::from_json(j, val), void())) = void]’
./nlohmann_json/json.hpp:1305:47:   required from ‘void nlohmann::detail::from_json_fn::operator()(const BasicJsonType&, T&) const [with BasicJsonType = nlohmann::basic_json<>; T = Person]’
./nlohmann_json/json.hpp:6822:30:   required from ‘static void nlohmann::adl_serializer< <template-parameter-1-1>, <template-parameter-1-2> >::from_json(BasicJsonType&&, ValueType&) [with BasicJsonType = const nlohmann::basic_json<>&; ValueType = Person; <template-parameter-1-1> = Person; <template-parameter-1-2> = void]’
./nlohmann_json/json.hpp:9461:45:   required from ‘ValueType nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>::get() const [with ValueTypeCV = Person; ValueType = Person; typename std::enable_if<(((! std::is_same<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>, ValueType>::value) && nlohmann::detail::has_from_json<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>, ValueType>::value) && (! nlohmann::detail::has_non_default_from_json<nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer>, ValueType>::value)), int>::type <anonymous> = 0; ObjectType = std::map; ArrayType = std::vector; StringType = std::basic_string<char>; BooleanType = bool; NumberIntegerType = long int; NumberUnsignedType = long unsigned int; NumberFloatType = double; AllocatorType = std::allocator; JSONSerializer = nlohmann::adl_serializer]’
main.cpp:97:37:   required from here
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/stl_pair.h:145:64: error: call of overloaded ‘vector(const nlohmann::basic_json<>&)’ is ambiguous
  : first(std::forward<_U1>(__x)), second(std::forward<_U2>(__y)) { }
                                                                ^
In file included from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/vector:64:0,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/random.h:34,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/random:49,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/stl_algo.h:66,
                 from /opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/algorithm:62,
                 from ./nlohmann_json/json.hpp:32,
                 from main.cpp:4:
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/stl_vector.h:373:7: note: candidate: std::vector<_Tp, _Alloc>::vector(std::initializer_list<_Tp>, const allocator_type&) [with _Tp = MovieInfo; _Alloc = std::allocator<MovieInfo>; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<MovieInfo>]
       vector(initializer_list<value_type> __l,
       ^
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/stl_vector.h:335:7: note: candidate: std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>&&) [with _Tp = MovieInfo; _Alloc = std::allocator<MovieInfo>]
       vector(vector&& __x) noexcept
       ^
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/stl_vector.h:318:7: note: candidate: std::vector<_Tp, _Alloc>::vector(const std::vector<_Tp, _Alloc>&) [with _Tp = MovieInfo; _Alloc = std::allocator<MovieInfo>]
       vector(const vector& __x)
       ^
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/stl_vector.h:277:7: note: candidate: std::vector<_Tp, _Alloc>::vector(std::vector<_Tp, _Alloc>::size_type, const allocator_type&) [with _Tp = MovieInfo; _Alloc = std::allocator<MovieInfo>; std::vector<_Tp, _Alloc>::size_type = long unsigned int; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<MovieInfo>]
       vector(size_type __n, const allocator_type& __a = allocator_type())
       ^
/opt/rh/devtoolset-4/root/usr/include/c++/5.3.1/bits/stl_vector.h:264:7: note: candidate: std::vector<_Tp, _Alloc>::vector(const allocator_type&) [with _Tp = MovieInfo; _Alloc = std::allocator<MovieInfo>; std::vector<_Tp, _Alloc>::allocator_type = std::allocator<MovieInfo>]
       vector(const allocator_type& __a) _GLIBCXX_NOEXCEPT
       ^
make: *** [main.o] Error 1
</pre>

**Comment by eliasdaler** [comment]
Hello
This looks like a nlohmann's json problem. Can you try out [the latest version](https://github.com/nlohmann/json/releases/tag/v3.2.0) and see if it works for you?

**Comment by brewc983** [comment]
It seems there is a JSON library compatibility issue with versions of GCC below 6. I finally got the example to compile using devtoolset-5 (g++ (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3)). Anything below that (e.g. g++ 4.9.2 and g++ 5.3.1) produced the errors mentioned above. 

I guess I will move on using that version of the compiler.

THANKS!

**Comment by eliasdaler** [comment]
Okay. :)

I might try to use a bit less demanding JSON library for examples, as it's not really important which library is used. Maybe MetaStuff then can be used with GCC < 6.
