### ISSUE TITLE
to_json and from_json not working when using namespaces.

### ISSUE THREAD

**Issue by Hindrik1997** [eliasdaler/MetaStuff#30]
When defining a type in a namespace and using the nlohmann JSON library, it cannot resolve the to_json and from_json functions. Putting the type in the global namespace makes it work again.

**Comment by eliasdaler** [comment]
Can you provide a simple example? I think that it should work due to ADL, it's strange that it doesn't
Maybe I need to rewrite a JSON example a bit. :)

**Comment by Hindrik1997** [comment]
First, I created the following macro's for easier member serialization:

`#define SERIALIZE_START(Type) namespace meta { \
    template <> \
    inline auto registerMembers<Type>() \
    { \
        return members( \

#define SERIALIZE_MEMBER(name, member_var) member(name, &member_var)
#define SERIALIZE_GETSET(name, member_get, member_set) member(name, &member_get, &member_set)

#define SERIALIZE_END ); \
    } \
}`

If I define the following code in a header file:

`#include <MetaStuff/JsonCast.h>
#include <MetaStuff/Meta.h>
#include "SerializeMacro.h"

#include <string>
#include <cstdint>
#include "Vectors.h"

struct TestStructure {
    string name;
    int value;
};


SERIALIZE_START(TestStructure)
    SERIALIZE_MEMBER("name", TestStructure::name),
    SERIALIZE_MEMBER("value", TestStructure::value)
SERIALIZE_END`

It works fine. I can call json.get<TestStructure>() to get my TestStructure object. 
However, as soon as I declare a namespace around the TestStructure, say namespace Serializable, it stops working:

`
/Users/hindrikstegenga/Repos/VKRenderer/sources/Main.cpp:47:36: error: no matching member function for call to 'get'
    TestStructure structure = test.get<TestStructure>();
                              ~~~~~^~~~~~~~~~~~~~~~~~
/Users/hindrikstegenga/Repos/VKRenderer/libraries/nlohmannJSON/json.hpp:14883:12: note: candidate template ignored: requirement 'std::is_same<typename std::remove_const<TestStructure>::type, basic_json_t>::value' was not satisfied [with BasicJsonType = Serializable::TestStructure]
basic_json get() const
           ^
/Users/hindrikstegenga/Repos/VKRenderer/libraries/nlohmannJSON/json.hpp:14906:15: note: candidate template ignored: requirement 'detail::is_basic_json<TestStructure>::value' was not satisfied [with BasicJsonType = Serializable::TestStructure]
BasicJsonType get() const
              ^
/Users/hindrikstegenga/Repos/VKRenderer/libraries/nlohmannJSON/json.hpp:14956:11: note: candidate template ignored: requirement 'detail::has_from_json<basic_json_t, TestStructure>::value' was not satisfied [with ValueTypeCV = Serializable::TestStructure, ValueType = Serializable::TestStructure]
ValueType get() const noexcept(noexcept(
          ^
/Users/hindrikstegenga/Repos/VKRenderer/libraries/nlohmannJSON/json.hpp:15007:11: note: candidate template ignored: requirement 'detail::has_non_default_from_json<basic_json_t, TestStructure>::value' was not satisfied [with ValueTypeCV = Serializable::TestStructure, ValueType = Serializable::TestStructure]
ValueType get() const noexcept(noexcept(
          ^
/Users/hindrikstegenga/Repos/VKRenderer/libraries/nlohmannJSON/json.hpp:15137:6: note: candidate template ignored: substitution failure [with PointerType = Serializable::TestStructure]: no matching member function for call to 'get_ptr'
auto get() noexcept -> decltype(std::declval<basic_json_t&>().template get_ptr<PointerType>())
     ^                                                                 ~~~~~~~
/Users/hindrikstegenga/Repos/VKRenderer/libraries/nlohmannJSON/json.hpp:15149:16: note: candidate template ignored: substitution failure [with PointerType = Serializable::TestStructure]: no matching member function for call to 'get_ptr'
constexpr auto get() const noexcept -> decltype(std::declval<const basic_json_t&>().template get_ptr<PointerType>())
               ^                                                                             ~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/VKRenderer.dir/sources/Main.cpp.o] Error 1
make[1]: *** [CMakeFiles/VKRenderer.dir/all] Error 2
make: *** [all] Error 2`

**Comment by eliasdaler** [comment]
I see, thanks for the example! I'll see what I can do on this weekend. 

Btw, if you declare to_json/from_json yourself for nlohmann's json (without using MetaStuff), does it work okay with namespaces in your case?

**Comment by eliasdaler** [comment]
Okay, I've found the solution. You need to do this:

```cpp
namespace Serializable {
    void from_json(const json& j, TestStructure& obj) {
        meta::deserialize(obj, j);
    }
    void to_json(json & j, const TestStructure& obj) {
        j = meta::serialize(obj);
    }
}
```

That's because nlohmann's json searches for to/from_json in the same namespace that the type has. I don't think this can be automated in some way (by default to/from_json are defined in global namespace in JsonCast.inl)

**Comment by Hindrik1997** [comment]
Awesome! Thank you kindly!
